volumes:
  kong_db_data: {}
  mongo_db_data: {}

x-kong-config: &kong-env
  KONG_DATABASE: postgres
  KONG_PG_HOST: kong-ee-database
  KONG_PG_DATABASE: kong
  KONG_PG_USER: kong
  KONG_PG_PASSWORD: kong

services:
  mongo:
    image: mongo:5
    container_name: mongo
    networks:
      - netflix
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_db_data:/data/db
    ports:
      - 27018:27017

  netflix-db-api:
    image: faragoeszter/netflix-db-api:latest
    container_name: netflix-db-api
    networks:
      - netflix
    environment:
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - MONGO_HOST
      - MONGO_PORT
      - MONGO_DB_NAME
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:4000/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
    restart: on-failure
    depends_on:
      - mongo
  netflix-api:
    image: faragoeszter/netflix-api:latest
    container_name: netflix-api
    networks:
      - netflix
    environment:
      - DB_API_URL
      - KONG_ADMIN_API_URL
      - ADMIN_API_KEY
    depends_on:
      netflix-db-api:
        condition: service_healthy
  netflix-api2:
    image: faragoeszter/netflix-api:latest
    container_name: netflix-api2
    networks:
      - netflix
    environment:
      - DB_API_URL
      - KONG_ADMIN_API_URL
      - ADMIN_API_KEY
    depends_on:
      netflix-db-api:
        condition: service_healthy

  kong-ee-database:
    container_name: kong-ee-database
    image: postgres:latest
    restart: on-failure
    volumes:
      - kong_db_data:/var/lib/postgresql
    networks:
      - netflix
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 10s
      retries: 10

  kong-bootstrap:
    image: kong:3.4.2
    container_name: kong-bootstrap
    networks:
      - netflix
    depends_on:
      kong-ee-database:
        condition: service_healthy
    restart: on-failure
    environment:
      <<: *kong-env
    command: kong migrations bootstrap

  kong:
    image: kong:3.4.2
    container_name: kong
    restart: on-failure
    networks:
      - netflix
    environment:
      <<: *kong-env
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
      KONG_ADMIN_GUI_URL: http://${GW_HOST:-localhost}:82
    depends_on:
      kong-bootstrap:
        condition: service_completed_successfully
      netflix-api:
        condition: service_started
      netflix-api2:
        condition: service_started
    ports:
      - "80:8000"
      - "8001:8001"
      - "82:8002"

networks:
  netflix:
    name: netflix
    driver: bridge
